name: tests


on: [push, pull_request]

jobs:
  
  Carla_linux:
      runs-on: [ubuntu-18.04]          
      steps:
        - uses: actions/checkout@v2
        - name: Dependencies
          run: |
            sudo apt-get update &&
            sudo apt-get install wget software-properties-common &&
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test &&
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - &&
            sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main" &&
            sudo apt-get update
            sudo apt-get install build-essential clang-8 lld-8 g++-7 cmake ninja-build libvulkan1 python python-pip python-dev python3-dev python3-pip libpng-dev libtiff5-dev libjpeg-dev tzdata sed curl unzip autoconf libtool rsync libxml2-dev git
            sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-8/bin/clang++ 180 &&
            sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-8/bin/clang 180
            
        - name: Python dependencies
          run: |
            pip install --upgrade pip
            pip3 install --upgrade pip
            pip install --user setuptools &&
            pip3 install --user -Iv setuptools==47.3.1 &&
            pip install --user distro &&
            pip3 install --user distro &&
            pip install --user wheel &&
            pip3 install --user wheel auditwheel
            pip3 install -q --user setuptools
            pip3 install -q --user -r PythonAPI/test/requirements.txt
            pip3 install -q --user -r PythonAPI/carla/requirements.txt  
            
        - name: Test Make
          run: |
            while sleep 2m; do echo "still building..."; done &
            make setup
            make LibCarla
            make PythonAPI
            make examples
            make check ARGS="--all --gtest_args=--gtest_filter=-*_mt"
            
        - name: Pylint 2 
          run: |
            pip install --upgrade pip
            pip install --user setuptools
            pip install --user distro
            pip install --user wheel
            pip install -q --user pylint
            pip install -q --user -r PythonAPI/carla/requirements.txt
            pip install -q --user -r PythonAPI/test/requirements.txt
            pip install -q --user -r PythonAPI/util/requirements.txt
            pip install -q --user -r PythonAPI/examples/requirements.txt
            shopt -s globstar
            pylint --exit-zero --disable=R,C --rcfile=PythonAPI/.pylintrc PythonAPI/**/*.py Util/BuildTools/*.py
            
        - name: Pylint 3
          run: |
            pip3 install --upgrade pip
            pip3 install --user -Iv setuptools==47.3.1
            pip3 install --user distro &&
            pip3 install --user wheel auditwheel
            pip3 install -q --user -r PythonAPI/test/requirements.txt
            pip3 install -q --user -r PythonAPI/carla/requirements.txt
            pip3 install -q astroid==2.2.5 pylint==2.3.1
            pip3 install -q --user -r PythonAPI/carla/requirements.txt
            pip3 install -q --user -r PythonAPI/examples/requirements.txt
            pip3 install -q --user -r PythonAPI/test/requirements.txt
            pip3 install -q --user -r PythonAPI/util/requirements.txt
            pip3 install -q --user -r Util/Docker/requirements.txt
            shopt -s globstar
            pylint --exit-zero --disable=R,C --rcfile=PythonAPI/.pylintrc PythonAPI/**/*.py Util/Docker/*.py Util/BuildTools/*.py
      
